### ISSUE TITLE
功能点疑问

### ISSUE THREAD

**Issue by DopX** [TRYtoBest/ChatGPT-dingtalk-bot#1]
是否可以针对每个钉钉用户和用户所在组限制使用次数

**Comment by whatifuwill** [comment]
只是一个简易的钉钉机器人调用，由于使用outgoing机制，不同群使用需要配置不同的机器人、

**Comment by ytanck** [comment]
大佬请看
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/www/ChatGPT-dingtalk-bot/webhook.py", line 35, in event
    chatgpt_response=requests.post('https://api.openai.com/v1/chat/completions',headers=headers,json=json_message,proxies=proxies)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2afe22e470>: Failed to establish a new connection: [Errno 111] Connection refused',)))

是因为没开代理导致的吗，Linux怎么开启clash，

**Comment by whatifuwill** [comment]
超时了。代理多换几个节点试试，我自己也经常这样。

**Comment by whatifuwill** [comment]
没在linux跑过抱歉，但是应该有解决办法。

**Comment by whatifuwill** [comment]
或者是api没有额度导致，充值就可以了 @DopX @ytking
